version: '3.9'

services:

  postgres:
    image: 'postgres:16.3'
    restart: always
    # TODO remove this - expose port 5432 to host for using with dBeaver
    ports:
      - "5432:5432"
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    volumes:
      - ./src/main/resources/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    environment:
      - "POSTGRES_DB=ecommerce"
      - "POSTGRES_USER=admin"
      - "POSTGRES_PASSWORD=password"

  adminer:
    image: adminer
    restart: always
    ports:
      - "8090:8080"

